export const productsConst = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL',
    DELETE_PRODUCT: 'DELETE_PRODUCT',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAIL: 'DELETE_PRODUCT_FAIL'
}
export const recipesConst = {
    ADD_RECIPE: 'ADD_RECIPE',
    ADD_RECIPE_SUCCESS: 'ADD_RECIPE_SUCCESS',
    ADD_RECIPE_FAIL: 'ADD_RECIPE_FAIL',
    GET_RECIPES: 'GET_RECIPES',
    GET_RECIPES_SUCCESS: 'GET_RECIPES_SUCCESS',
    GET_RECIPES_FAIL: 'GET_RECIPES_FAIL',
    DELETE_RECIPE: 'DELETE_RECIPE',
    DELETE_RECIPE_SUCCESS: 'DELETE_RECIPE_SUCCESS',
    DELETE_RECIPE_FAIL: 'DELETE_RECIPE_FAIL'
}
export const loginConst = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_HANDLE_CHANGE: 'LOGIN_HANDLE_CHANGE'
}
export const snackBarConst = {
    SNACKBAR_OPEN: 'SNACKBAR_OPEN',
    SNACKBAR_CLOSE: 'SNACKBAR_CLOSE'
}

export const stepperConst = {
    NEXT_STEP: 'NEXT_STEP',
    PREVIOUS_STEP:'PREVIOUS_STEP'
}

// export const modalConst = {
//     MODAL_OPEN: 'MODAL_OPEN',
//     MODAL_CLOSE: 'MODAL_CLOSE',
//     MODAL_CLEAR: 'MODAL_CLEAR'
// }