export const productsConst = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_PRODUCT_SUCCESS: 'ADD_PRODUCT_SUCCESS',
    ADD_PRODUCT_FAIL: 'ADD_PRODUCT_FAIL',
    GET_PRODUCTS: 'GET_PRODUCTS',
    GET_PRODUCTS_SUCCESS: 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_FAIL: 'GET_PRODUCTS_FAIL'
}
export const recipesConst = {
    ADD_RECIPE: 'ADD_RECIPE',
    ADD_RECIPE_TODO_TASK: 'ADD_RECIPE_TODO_TASK',
    GET_RECIPES: 'GET_RECIPES'
}
export const loginConst = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_HANDLE_CHANGE: 'LOGIN_HANDLE_CHANGE'
}