export const productsConst = {
    ADD_PRODUCT: 'ADD_PRODUCT',
    ADD_PRODUCT_PENDING: 'ADD_PRODUCT_PENDING',
    ADD_PRODUCT_FULFILLED: 'ADD_PRODUCT_FULFILLED',
    ADD_PRODUCT_REJECTED: 'ADD_PRODUCT_REJECTED',
    GET_PRODUCTS: 'GET_PRODUCTS'
}
export const recipesConst = {
    ADD_RECIPE: 'ADD_RECIPE',
    ADD_RECIPE_TODO_TASK: 'ADD_RECIPE_TODO_TASK',
    GET_RECIPES: 'GET_RECIPES'
}
export const loginConst = {
    LOGIN_USER: 'LOGIN_USER',
    LOGIN_HANDLE_CHANGE: 'LOGIN_HANDLE_CHANGE'
}